title: EzMode
description: The Easiest EzMode of all EzModes
social_link: Facebook
social_username: EzMode
github_repo: EzMode
github_username: TheEasy Man Mode
theme_color: Blue
remote_theme: internet-de-france/swiss
baseurl: /theezmode
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
